server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Hada howa ssr: dima kayrj3 l'index.html ila mal9ach l'fichier
    location / {
        try_files $uri $uri/ /index.html;
    }
}